library(usethis)
use_mit_license("Gabriele Marini (marinig@student.unimelb.edu.au)")
use_package("ggplot2", "Suggests")
use_package("dplyr", "Imports")
use_package("data.table", "Imports")
use_package("rmdHelpers", "Imports")
use_package("utils", "Imports")
use_package("foreach", "Imports")
use_package("doParallel", "Imports")
use_package("stringr", "Imports")
use_package("lubridate", "Imports")
use_package("readr", "Imports")
use_package("dlm", "Imports")
use_readme_md()

use_test("agents-def")
use_test("rooms-def")
use_test("states-def")
